name: Build job
# Cloned from tachiyomi
on:
  # Every Saturday at 16:00 UTC-5
  #schedule:
  #  - cron: '0 21 * * 0,3'
  # Manual triggers
  workflow_dispatch:
    inputs:
      git-ref:
        description: Git Ref (Optional)
        required: false
      dry-run:
        description: Creates a draft release
        required: false

jobs:
  build-app:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repository (Latest)
        uses: actions/checkout@v2
        with:
          repository: 'mik3y/usb-serial-for-android'
          fetch-depth: 0
        if: github.event.inputs.git-ref == ''
      - name: Clone Repository (Custom Ref)
        uses: actions/checkout@v2
        if: github.event.inputs.git-ref != ''
        with:
          repository: 'mik3y/usb-serial-for-android'
          fetch-depth: 0
          ref: ${{ github.event.inputs.git-ref }}

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Build with Gradle
        run: ./gradlew assembleRelease

      - name: Create Release
        uses: actions/upload-artifact@v2
        with:
          name: usb-serial-for-android
          path: ./**/*.apk

      - name: Download Artifacts
        uses: actions/download-artifact@v2
        with:
          name: usb-serial-for-android
